### ISSUE TITLE
链接失效

### ISSUE THREAD

**Issue by gocpplua** [roomai/RoomAI#34]
https://github.com/roomai/RoomAI/blob/master/docs/document/guides_ai.md 页面的最后一个超链接：The code of this example is shown here 失效了：
https://github.com/roomai/RoomAI/blob/master/example/aggressive_kuhn.py  not found

**Comment by algorithmdog** [comment]
这个项目已经停止了，因为我们发现两个更好的项目，继续做这个项目没啥意义了:
https://github.com/dickreuter/Poker
https://github.com/ishikota/PyPokerEngine
